pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: ./src/hal/dotnet-and-hal-browser/Server.csproj
    arguments: --configuration Release
  displayName: Build
